services:
  web:
    build: ./fe
    container_name: front
    ports:
      - "5002:5002"
    depends_on:
      - backend-service
    networks:
      - liad_network

  backend-service:
    build: ./be
    container_name: back
    ports:
      - "5003:5001"
    depends_on:
      - mysqldb
    environment:
        MYSQL_HOST: mysqldb
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456
        MYSQL_DATABASE: crypto_db
    networks:
      - liad_network
    

  mysqldb:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: crypto_db
    ports:
      - "3306:3306"
    networks:
      - liad_network

networks:
  liad_network:
    driver: bridge
      